### ISSUE TITLE
How do I call OnModelCreating

### ISSUE THREAD

**Issue by integral-llc** [cup-of-tea-dot-be/entity-framework-core-mock#19]
All of me Entities do not use attributes to mark the keys, everything is happening inside `OnModelCreating` override method. 
i.e.
```
modelBuilder.Entity<MarketplaceEntity>(entity =>
            {
                entity.ToTable("Marketplace", "Application");
                entity.HasKey(e => e.MarketplaceKey);
            });
```

How to call this method so the keys are properly initialized? As of now, I'm getting an exception saying the entity `does not contain any property marked with KeyAttribute`.

thx!

**Comment by huysentruitw** [comment]
Unfortunately entity configurations like that are currently not supported. As of now, I can't tell how complex it would be to add support for it. However, currently, you can work-around this by passing your own key-factory to the call to `CreateDbSetMock`.

```C#
dbContextMock.CreateDbSetMock(x => x.MarketPlaces, (entity, _) => entity.MarketplaceKey, initialEntities);
```
