### ISSUE TITLE
It doesn't work with entities that have no key.

### ISSUE THREAD

**Issue by mikesalway** [cup-of-tea-dot-be/entity-framework-core-mock#31]
I have an entity from a view, with no key available and is marked with (entity.HasNoKey();)  I therefore can't create mock entities, I just get this error

No key factory could be created for entity type

Any suggestions?

**Comment by huysentruitw** [comment]
In case of keyless entities, you'll need to pass a key factory yourself.

This can be as simple as: `(x, _) => x` to use the entire model as key or `(x, _) => x.Id` if there is a property that can be used as a key (Id in this example).

The above is demonstrated in [this unit-test](https://github.com/cup-of-tea-dot-be/entity-framework-core-mock/blob/master/tests/EntityFrameworkCoreMock.Moq.Tests/DbContextMockTests.cs#L114)
