### ISSUE TITLE
Working with Attach and Entry Methods

### ISSUE THREAD

**Issue by GeorgyRezchikov** [cup-of-tea-dot-be/entity-framework-core-mock#34]
Hello!

I have an example code like this:
```
var contract = new AgentContract { Id = contractId, MasterSystem = masterSystem};
_context.AgentContracts.Attach(contract);
var entry = _context.Entry(contract);
```
after calling the Entri method, I get a null object **entry**.

As I assume the Attach method does not add the object to the context, can this be fixed?

**EF Core 5.0.2**
**EntityFrameworkCoreMock.Moq 2.1.0**
**EntityFrameworkCoreMock.NSubstitute 2.1.0**

**Comment by huysentruitw** [comment]
This is currently not supported. I took a minute to look into this and I think it is not easy to implement as it would require us to mimic the EF Core change tracker. I think for use-cases like this, it might be better to test with the InMemoryDatabase provider:

```C#
var options = new DbContextOptionsBuilder<MyDbContext>()
    .UseInMemoryDatabase("MyDatabase")
    .Options;
  
context = new MyDbContext(options);
```

**Comment by GeorgyRezchikov** [comment]
Thanks for the answer!
