### ISSUE TITLE
Why does DbContextMock.Object.Entry(entry) return null 

### ISSUE THREAD

**Issue by mzmoosa01** [cup-of-tea-dot-be/entity-framework-core-mock#35]
## Context
I'm trying to test a Put method and when the DbContextMock.Object.Entry(entry) seems to always return null 
 
## Recreating the issue
* Create a mocked dbContext
* Populate the mocked dbContext with entities 
* Attempt to retrieve one of the entities using DbContextMock.Object.Entry(entry)
*  This will return null 

I'm not sure if this is expected or if I'm doing something wrong perhaps.

**Comment by huysentruitw** [comment]
See #34

**Comment by mzmoosa01** [comment]
Thank you for the response. I don't understand how using an in-memory database helps with this issue though. I'm trying to test a put method that should update my Db.

**Comment by mzmoosa01** [comment]
I apologize, I am a little bit of a newby. Let me re-phrase my question. I'm trying to test CRUD Api operations and I'm stuck on testing the Put method that should update the Db. Below is my code for the actual method: 
`[HttpPut("{id}")]
        public async Task<IActionResult> PutPhoto(long id, Photo photo)
        {
            if (id != photo.photoId)
            {
                return BadRequest();
            }

            _context.Entry(photo).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PhotoExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }`

Any test I write for this is failing because the _context.Entry(photo).State = EntityState.Modified; returns null.
