### ISSUE TITLE
DbSet AsQueryable() returns empty list instead of data and crash on ToListAsync()

### ISSUE THREAD

**Issue by codingyourlife** [cup-of-tea-dot-be/entity-framework-core-mock#36]
In the attached screenshots you can see that the result of my ServiceSet table contains data but calling .AsQueryable() on it does not return any data so the variable is an empty list (see other image).

Furthermore my UnitTest crashes in this function if I use ToListAsync(). If I use ToList() it works but I just realized that the test doesn't seem to work right then.

Is this a bug or can this be configured/mocked somehow?

Here you can see there is mocked data in the table:
<img width="966" alt="Screenshot 2021-06-24 at 22 29 22" src="https://user-images.githubusercontent.com/10122382/123329572-3f7fe600-d53d-11eb-835d-45fef9316cf4.png">

And it gets lost when calling .AsQueryable() on it:
<img width="723" alt="Screenshot 2021-06-24 at 22 29 36" src="https://user-images.githubusercontent.com/10122382/123329579-4149a980-d53d-11eb-8cb4-bbe00c79ed6b.png">

**Comment by huysentruitw** [comment]
Can you provide a unit-test or minimal reproducible example that demonstrates the issue?

**Comment by codingyourlife** [comment]
Sure. Was also interested in looking a bit deeper and created a Fork and a Pullrequest:
https://github.com/cup-of-tea-dot-be/entity-framework-core-mock/pull/37/files

Sadly nothing you can blindly merge but I did my best.

I meanwhile also needed the .Entry(myDbset) function so I reference issue https://github.com/cup-of-tea-dot-be/entity-framework-core-mock/issues/34 which I also created a basic unit test for that fails.

I think I could successfully fix the .AsQueryable() function but I'm not experienced in Moq enough to mock the .Entry() method. I hope you can figure it out and that I can learn from your addition :)

**Comment by codingyourlife** [comment]
@huysentruitw friendly ping :). Will you have time for this any time soon?

**Comment by codingyourlife** [comment]
FINALLY figured out at least a workaround. Instead of using `.AsQueryable()` you can write `.Include(x => x)`. Looks like it does nothing but it ensures that you have an IQueryable instead of an IEnumerable.
